name = "ruoshui-forum-api"
main = "src/worker.ts"
compatibility_date = "2026-04-17"

[vars]
CORS_ORIGIN = "https://ruoshui-web.pages.dev"
MEDIA_BUCKET_NAME = "ruoshui-media"
MEDIA_PUBLIC_BASE_URL = "https://pub-5fbf37dd49b94b859c13e343effd0430.r2.dev"
PUBLIC_API_BASE_URL = "https://ruoshui-forum-api.tazdingo-ruoshui.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "ruoshui-forum"
database_id = "77f54654-bb08-41b4-afb4-cfd1c3669a26"
preview_database_id = "77f54654-bb08-41b4-afb4-cfd1c3669a26"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "ruoshui-media"
preview_bucket_name = "ruoshui-media-preview"
